{% set name = "pyribs-base" %}
{% set pypi_name = "ribs" %}
{% set version = "0.5.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ pypi_name[0] }}/{{ pypi_name }}/ribs-{{ version }}.tar.gz
  sha256: 89b32a8f540df9cb1f9b363c91ef567fe83556337e1309e0dce78e18d27d21a0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - decorator >=4.0.0
    - numba >=0.51.0
    - numpy >=1.17.0
    - pandas >=1.0.0
    - python >=3.6
    - scikit-learn >=0.20
    - scipy >=1.4.0
    - sortedcontainers >=2.0.0
    - threadpoolctl >=2.0.0
    - toml >=0.10.0

test:
  imports:
    - ribs
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/icaros-usc/pyribs
  summary: The pyribs-base package on Conda is DEPRECATED. Please use the pyribs package on Conda instead.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - btjanaka
